# version: '3.7'

# services:
#   emsassist:
#     image: haroon3rd/anaconda3:nvidia-v1
#     container_name: emsassist
#     volumes:
#       - ./data:/home/EMSAssist-artifact-evaluation/data
#       - ./model:/home/EMSAssist-artifact-evaluation/model
#     #command: [/bin/bash -c "tail -f /dev/null"]
#     command: tail -F anything
#     #network_mode: "host"
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               capabilities: [gpu]
# volumes:
#   emsassist: {}

version: '3.7'

services:
  emsassist:
    image: liuyidockers/emsassist-ae:emsassist_final3
    container_name: emsassist
    volumes:
      - ./init_models:/home/EMSAssist/init_models
      - ./examples:/home/EMSAssist/examples
      - ./src:/home/EMSAssist/src
      - ./data:/home/EMSAssist/data
      - ./model:/home/EMSAssist/model
      - ./requirements.txt:/home/EMSAssist/requirements.txt
      - ./docker-compose.yml:/home/EMSAssist/docker-compose.yml
      # - .:/home/EMSAssist/.
    #command: [/bin/bash -c "tail -f /dev/null"]
    # command: tail -F anything
    #network_mode: "host"
    working_dir: /home/EMSAssist
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  emsassist: {}  

