version: '3.7'

services:
  emsassist:
    image: haroon3rd/anaconda3:nvidia-v1
    container_name: emsassist
    volumes:
      - ./data:/home/EMSAssist-artifact-evaluation/data
      - ./model:/home/EMSAssist-artifact-evaluation/model
    #command: [/bin/bash -c "tail -f /dev/null"]
    command: tail -F anything
    #network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
volumes:
  emsassist: {}

