ref_files:
    pri_sym: ESITUATION_09REF.txt
    pri_imp: ESITUATION_11REF.txt
    add_sym: ESITUATION_10REF.txt
    sec_imp: ESITUATION_12REF.txt
    pri_sym_desc: pri_sym_desc.txt
    add_sym_desc: add_sym_desc.txt
    pri_imp_desc: pri_imp_desc.txt
    sec_imp_desc: sec_imp_desc.txt
    pri_sym_desc_concept: pri_sym_desc_concept.txt
    add_sym_desc_concept: add_sym_desc_concept.txt
    pri_imp_desc_concept: pri_imp_desc_concept.txt
    sec_imp_desc_concept: sec_imp_desc_concept.txt
    pri_sym_code_concept: pri_sym_code_concept.txt
    add_sym_code_concept: add_sym_code_concept.txt
    pri_imp_code_concept: pri_imp_code_concept.txt
    sec_imp_code_concept: sec_imp_code_concept.txt
    pri_sym_desc_mml_concept: pri_sym_desc_mml_concept.txt
    add_sym_desc_mml_concept: add_sym_desc_mml_concept.txt
    pri_imp_desc_mml_concept: pri_imp_desc_mml_concept.txt
    sec_imp_desc_mml_concept: sec_imp_desc_mml_concept.txt
    pri_sym_code_mml_concept: pri_sym_code_mml_concept.txt
    add_sym_code_mml_concept: add_sym_code_mml_concept.txt
    pri_imp_code_mml_concept: pri_imp_code_mml_concept.txt
    sec_imp_code_mml_concept: sec_imp_code_mml_concept.txt
valid_files:
    pri_sym: Valid_FACTPCRPRIMARYSYMPTOM.txt
    add_sym: Valid_FACTPCRADDITIONALSYMPTOM.txt
    pri_imp: Valid_FACTPCRPRIMARYIMPRESSION.txt
    sec_imp: Valid_FACTPCRSECONDARYIMPRESSION.txt
    pri_sym_code_dict: Valid_code_dict_FACTPCRPRIMARYSYMPTOM.txt
    add_sym_code_dict: Valid_code_dict_FACTPCRADDITIONALSYMPTOM.txt
    pri_imp_code_dict: Valid_code_dict_FACTPCRPRIMARYIMPRESSION.txt
    sec_imp_code_dict: Valid_code_dict_FACTPCRSECONDARYIMPRESSION.txt
    pri_sym_dscp_dict: Valid_dscp_dict_FACTPCRPRIMARYSYMPTOM.txt
    add_sym_dscp_dict: Valid_dscp_dict_FACTPCRADDITIONALSYMPTOM.txt
    pri_imp_dscp_dict: Valid_dscp_dict_FACTPCRPRIMARYIMPRESSION.txt
    sec_imp_dscp_dict: Valid_dscp_dict_FACTPCRSECONDARYIMPRESSION.txt
    pri_sym_concept_dict: Valid_concept_dict_FACTPCRPRIMARYSYMPTOM.txt
    add_sym_concept_dict: Valid_concept_dict_FACTPCRADDITIONALSYMPTOM.txt
    pri_imp_concept_dict: Valid_concept_dict_FACTPCRPRIMARYIMPRESSION.txt
    sec_imp_concept_dict: Valid_concept_dict_FACTPCRSECONDARYIMPRESSION.txt
    pri_sym_concept_dict_nemsis_separator: Valid_concept_dict_FACTPCRPRIMARYSYMPTOM_nemsis_separator.txt    # This is for concept matching counts
    add_sym_concept_dict_nemsis_separator: Valid_concept_dict_FACTPCRADDITIONALSYMPTOM_nemsis_separator.txt
    pri_imp_concept_dict_nemsis_separator: Valid_concept_dict_FACTPCRPRIMARYIMPRESSION_nemsis_separator.txt
    sec_imp_concept_dict_nemsis_separator: Valid_concept_dict_FACTPCRSECONDARYIMPRESSION_nemsis_separator.txt
    pri_sym_mml_concept_dict: Valid_mml_concept_dict_FACTPCRPRIMARYSYMPTOM.txt
    add_sym_mml_concept_dict: Valid_mml_concept_dict_FACTPCRADDITIONALSYMPTOM.txt
    pri_imp_mml_concept_dict: Valid_mml_concept_dict_FACTPCRPRIMARYIMPRESSION.txt
    sec_imp_mml_concept_dict: Valid_mml_concept_dict_FACTPCRSECONDARYIMPRESSION.txt
    pri_sym_mml_concept_dict_nemsis_separator: Valid_mml_concept_dict_FACTPCRPRIMARYSYMPTOM_nemsis_separator.txt
    add_sym_mml_concept_dict_nemsis_separator: Valid_mml_concept_dict_FACTPCRADDITIONALSYMPTOM_nemsis_separator.txt
    pri_imp_mml_concept_dict_nemsis_separator: Valid_mml_concept_dict_FACTPCRPRIMARYIMPRESSION_nemsis_separator.txt
    sec_imp_mml_concept_dict_nemsis_separator: Valid_mml_concept_dict_FACTPCRSECONDARYIMPRESSION_nemsis_separator.txt
raw_files:
    pri_sym: FACTPCRPRIMARYSYMPTOM.txt
    pri_imp: FACTPCRPRIMARYIMPRESSION.txt
    add_sym: FACTPCRADDITIONALSYMPTOM.txt
    sec_imp: FACTPCRSECONDARYIMPRESSION.txt
protocol:
    file: 
        ori: FACTPCRPROTOCOL.txt
        filtered: filtered_nemsis_protocols.txt
        filtered_out: filtered_out_nemsis_protocols.txt
        no_filter: no_filter_nemsis_protocols.txt
        valid_adult: AdultProtocols.txt
        valid_gener: GeneralProtocols.txt
        valid_pedia: PediatricProtocols.txt
        fit: Fit_NEMSIS_To_TAMU_Revision1.tsv
        sign_concept_set: sign_concept_set.txt
        sign_hist_concept_set: sign_hist_concept_set.txt
        protocol_sign_list: protocol_sign_list.txt
        protocol_sign_hist_list: protocol_sign_hist_list.txt
        protocol_input_sign: protocol_input_sign.txt
        protocol_input_sign_hist: protocol_input_sign_hist.txt
        protocol_ids: protocol_ids.txt
        protocol_id2name: protocol_id2name.txt
        sep_eval_dir:
            pedia: SepEval/pedia/
            adult: SepEval/adult/
            gener: SepEval/gener/
            pedia_all: pedia_all.txt            # everything about pedia, protocols, concepts, inputs, ...
            adult_all: adult_all.txt
            gener_all: gener_all.txt
    fit_scheme: nemsis_fit_tamu    
    adult: '3602001'
    general: '3602003'
    pediatric: '3602005'
    na: '7701001'
    nr: '7701003'
input_files:
    pcr_filtered_protocol_ps_pi: pcr_filtered_protocol_ps_pi.txt
    pcr_filtered_protocol_ps_pi_as_si: pcr_filtered_protocol_ps_pi_as_si.txt
    filtered_ps_pi: filtered_ps_pi.txt
    filtered_ps_pi_as_si: filtered_ps_pi_as_si.txt
    filtered_unique_ps_pi: filtered_unique_ps_pi.txt
    filtered_unique_ps_pi_protocol: filtered_unique_ps_pi_protocol.txt
    filtered_unique_ps_pi_as_si: filtered_unique_ps_pi_as_si.txt
    filtered_unique_ps_pi_as_si_protocol: filtered_unique_ps_pi_as_si_protocol.txt
    pcr_filtered_protocol_ps_pi_c: pcr_filtered_protocol_ps_pi_c.txt
    pcr_filtered_protocol_ps_pi_as_si_c: pcr_filtered_protocol_ps_pi_as_si_c.txt
    filtered_ps_pi_c: filtered_ps_pi_c.txt
    filtered_ps_pi_as_si_c: filtered_ps_pi_as_si_c.txt
    pcr_filtered_protocol_ps_pi_mml_c: pcr_filtered_protocol_ps_pi_mml_c.txt
    pcr_filtered_protocol_ps_pi_as_si_mml_c: pcr_filtered_protocol_ps_pi_as_si_mml_c.txt
    filtered_ps_pi_mml_c: filtered_ps_pi_mml_c.txt
    filtered_ps_pi_as_si_mml_c: filtered_ps_pi_as_si_mml_c.txt
    pcr_filtered_protocol_ps_pi_desc_c_mml_c: pcr_filtered_protocol_ps_pi_desc_c_mml_c.txt
    pcr_filtered_protocol_ps_pi_as_si_desc_c_mml_c: pcr_filtered_protocol_ps_pi_as_si_desc_c_mml_c.txt
    filtered_ps_pi_desc_c_mml_c: filtered_ps_pi_desc_c_mml_c.txt
    filtered_ps_pi_as_si_desc_c_mml_c: filtered_ps_pi_as_si_desc_c_mml_c.txt
    pcr_filtered_protocol_ps_pi_desc_c: pcr_filtered_protocol_ps_pi_desc_c.txt
    pcr_filtered_protocol_ps_pi_as_si_desc_c: pcr_filtered_protocol_ps_pi_as_si_desc_c.txt
    filtered_ps_pi_desc_c: filtered_ps_pi_desc_c.txt
    filtered_ps_pi_as_si_desc_c: filtered_ps_pi_as_si_desc_c.txt
    pcr_filtered_protocol_ps_pi_desc_mml_c: pcr_filtered_protocol_ps_pi_desc_mml_c.txt
    pcr_filtered_protocol_ps_pi_as_si_desc_mml_c: pcr_filtered_protocol_ps_pi_as_si_desc_mml_c.txt
    filtered_ps_pi_desc_mml_c: filtered_ps_pi_desc_mml_c.txt
    filtered_ps_pi_as_si_desc_mml_c: filtered_ps_pi_as_si_desc_mml_c.txt
input_files_no_filter:
    pcr_no_filtered_protocol_ps_pi: pcr_no_filtered_protocol_ps_pi.txt
    pcr_no_filtered_protocol_ps_pi_as_si: pcr_no_filtered_protocol_ps_pi_as_si.txt
    no_filtered_ps_pi: no_filtered_ps_pi.txt
    no_filtered_ps_pi_as_si: no_filtered_ps_pi_as_si.txt
    no_filtered_unique_ps_pi: no_filtered_unique_ps_pi.txt
    no_filtered_unique_ps_pi_protocol: no_filtered_unique_ps_pi_protocol.txt
    no_filtered_unique_ps_pi_as_si: no_filtered_unique_ps_pi_as_si.txt
    no_filtered_unique_ps_pi_as_si_protocol: no_filtered_unique_ps_pi_as_si_protocol.txt
    pcr_no_filtered_protocol_ps_pi_c: pcr_no_filtered_protocol_ps_pi_c.txt
    pcr_no_filtered_protocol_ps_pi_as_si_c: pcr_no_filtered_protocol_ps_pi_as_si_c.txt
    no_filtered_ps_pi_c: no_filtered_ps_pi_c.txt
    no_filtered_ps_pi_as_si_c: no_filtered_ps_pi_as_si_c.txt
    pcr_no_filtered_protocol_ps_pi_mml_c: pcr_no_filtered_protocol_ps_pi_mml_c.txt
    pcr_no_filtered_protocol_ps_pi_as_si_mml_c: pcr_no_filtered_protocol_ps_pi_as_si_mml_c.txt
    no_filtered_ps_pi_mml_c: no_filtered_ps_pi_mml_c.txt
    no_filtered_ps_pi_as_si_mml_c: no_filtered_ps_pi_as_si_mml_c.txt
    pcr_no_filtered_protocol_ps_pi_desc_c_mml_c: pcr_no_filtered_protocol_ps_pi_desc_c_mml_c.txt
    pcr_no_filtered_protocol_ps_pi_as_si_desc_c_mml_c: pcr_no_filtered_protocol_ps_pi_as_si_desc_c_mml_c.txt
    no_filtered_ps_pi_desc_c_mml_c: no_filtered_ps_pi_desc_c_mml_c.txt
    no_filtered_ps_pi_as_si_desc_c_mml_c: no_filtered_ps_pi_as_si_desc_c_mml_c.txt
    pcr_no_filtered_protocol_ps_pi_desc_mml_c: pcr_no_filtered_protocol_ps_pi_desc_mml_c.txt
    pcr_no_filtered_protocol_ps_pi_as_si_desc_mml_c: pcr_no_filtered_protocol_ps_pi_as_si_desc_mml_c.txt
    no_filtered_ps_pi_desc_mml_c: no_filtered_ps_pi_desc_mml_c.txt
    no_filtered_ps_pi_as_si_desc_mml_c: no_filtered_ps_pi_as_si_desc_mml_c.txt
bottleneck_files:
    pcr_ps_pi_as_si_c: bottleneck_pcr_ps_pi_as_si_c.txt
    dedup_pcr_ps_pi_as_si_c: dedup_bottleneck_pcr_ps_pi_as_si_c.txt
    ps_pi_as_si_c: bottleneck_ps_pi_as_si_c.txt
    dedup_ps_pi_as_si_c: dedup_bottleneck_ps_pi_as_si_c.txt
    pcr_ps_pi_as_si_mml_c: bottleneck_pcr_ps_pi_as_si_mml_c.txt
    dedup_pcr_ps_pi_as_si_mml_c: dedup_bottleneck_pcr_ps_pi_as_si_mml_c.txt
    ps_pi_as_si_mml_c: bottleneck_ps_pi_as_si_mml_c.txt
    dedup_ps_pi_as_si_mml_c: dedup_bottleneck_ps_pi_as_si_mml_c.txt
    nemsis_c_set: nemsis_c_set.txt
    nemsis_mmlc_set: nemsis_mmlc_set.txt
    nemsis_protocol_list: nemsis_protocol_list.txt
deduplicated_input_files:
    filtered_ps_pi_as_si_desc_multi_label: deduplicated_filtered_ps_pi_as_si_desc_multi_label.txt
    filtered_protocol_ps_pi_as_si_desc_multi_label: deduplicated_filtered_protocol_ps_pi_as_si_desc_multi_label.txt
    filtered_ps_pi_as_si_c_multi_label: deduplicated_filtered_ps_pi_as_si_c_multi_label.txt
    filtered_protocol_ps_pi_as_si_c_multi_label: deduplicated_filtered_protocol_ps_pi_as_si_c_multi_label.txt
    filtered_ps_pi_as_si_mml_c_multi_label: deduplicated_filtered_ps_pi_as_si_mml_c_multi_label.txt
    filtered_protocol_ps_pi_as_si_mml_c_multi_label: deduplicated_filtered_protocol_ps_pi_as_si_mml_c_multi_label.txt
    filtered_ps_pi_as_si_desc_c_mml_c_multi_label: deduplicated_filtered_ps_pi_as_si_desc_c_mml_c_multi_label.txt
    filtered_protocol_ps_pi_as_si_desc_c_mml_c_multi_label: deduplicated_filtered_protocol_ps_pi_as_si_desc_c_mml_c_multi_label.txt
    filtered_ps_pi_as_si_desc_single_label: deduplicated_filtered_ps_pi_as_si_desc_single_label.txt
    filtered_protocol_ps_pi_as_si_desc_single_label: deduplicated_filtered_protocol_ps_pi_as_si_desc_single_label.txt
    filtered_ps_pi_as_si_c_single_label: deduplicated_filtered_ps_pi_as_si_c_single_label.txt
    filtered_protocol_ps_pi_as_si_c_single_label: deduplicated_filtered_protocol_ps_pi_as_si_c_single_label.txt
    filtered_ps_pi_as_si_mml_c_single_label: deduplicated_filtered_ps_pi_as_si_mml_c_single_label.txt
    filtered_protocol_ps_pi_as_si_mml_c_single_label: deduplicated_filtered_protocol_ps_pi_as_si_mml_c_single_label.txt
    filtered_ps_pi_as_si_desc_c_mml_c_single_label: deduplicated_filtered_ps_pi_as_si_desc_c_mml_c_single_label.txt
    filtered_protocol_ps_pi_as_si_desc_c_mml_c_single_label: deduplicated_filtered_protocol_ps_pi_as_si_desc_c_mml_c_single_label.txt
    filtered_ps_pi_as_si_desc_c_single_label: deduplicated_filtered_ps_pi_as_si_desc_c_single_label.txt
    filtered_protocol_ps_pi_as_si_desc_c_single_label: deduplicated_filtered_protocol_ps_pi_as_si_desc_c_single_label.txt
    filtered_ps_pi_as_si_desc_mml_c_single_label: deduplicated_filtered_ps_pi_as_si_desc_mml_c_single_label.txt
    filtered_protocol_ps_pi_as_si_desc_mml_c_single_label: deduplicated_filtered_protocol_ps_pi_as_si_desc_mml_c_single_label.txt
    no_filtered_ps_pi_as_si_desc_single_label: deduplicated_no_filtered_ps_pi_as_si_desc_single_label.txt
    no_filtered_protocol_ps_pi_as_si_desc_single_label: deduplicated_no_filtered_protocol_ps_pi_as_si_desc_single_label.txt
    no_filtered_ps_pi_as_si_c_single_label: deduplicated_no_filtered_ps_pi_as_si_c_single_label.txt
    no_filtered_protocol_ps_pi_as_si_c_single_label: deduplicated_no_filtered_protocol_ps_pi_as_si_c_single_label.txt
    no_filtered_ps_pi_as_si_mml_c_single_label: deduplicated_no_filtered_ps_pi_as_si_mml_c_single_label.txt
    no_filtered_protocol_ps_pi_as_si_mml_c_single_label: deduplicated_no_filtered_protocol_ps_pi_as_si_mml_c_single_label.txt
    no_filtered_ps_pi_as_si_desc_c_mml_c_single_label: deduplicated_no_filtered_ps_pi_as_si_desc_c_mml_c_single_label.txt
    no_filtered_protocol_ps_pi_as_si_desc_c_mml_c_single_label: deduplicated_no_filtered_protocol_ps_pi_as_si_desc_c_mml_c_single_label.txt
    no_filtered_ps_pi_as_si_desc_mml_c_single_label: deduplicated_no_filtered_ps_pi_as_si_desc_mml_c_single_label.txt
    no_filtered_protocol_ps_pi_as_si_desc_mml_c_single_label: deduplicated_no_filtered_protocol_ps_pi_as_si_desc_mml_c_single_label.txt
    filtered_ps_pi_desc_single_label: deduplicated_filtered_ps_pi_desc_single_label.txt
    filtered_protocol_ps_pi_desc_single_label: deduplicated_filtered_protocol_ps_pi_desc_single_label.txt
    filtered_ps_pi_c_single_label: deduplicated_filtered_ps_pi_c_single_label.txt
    filtered_protocol_ps_pi_c_single_label: deduplicated_filtered_protocol_ps_pi_c_single_label.txt
    filtered_ps_pi_mml_c_single_label: deduplicated_filtered_ps_pi_mml_c_single_label.txt
    filtered_protocol_ps_pi_mml_c_single_label: deduplicated_filtered_protocol_ps_pi_mml_c_single_label.txt
    filtered_ps_pi_desc_c_mml_c_single_label: deduplicated_filtered_ps_pi_desc_c_mml_c_single_label.txt
    filtered_protocol_ps_pi_desc_c_mml_c_single_label: deduplicated_filtered_protocol_ps_pi_desc_c_mml_c_single_label.txt
    no_filtered_ps_pi_desc_single_label: deduplicated_no_filtered_ps_pi_desc_single_label.txt
    no_filtered_protocol_ps_pi_desc_single_label: deduplicated_no_filtered_protocol_ps_pi_desc_single_label.txt
    no_filtered_ps_pi_c_single_label: deduplicated_no_filtered_ps_pi_c_single_label.txt
    no_filtered_protocol_ps_pi_c_single_label: deduplicated_no_filtered_protocol_ps_pi_c_single_label.txt
    no_filtered_ps_pi_mml_c_single_label: deduplicated_no_filtered_ps_pi_mml_c_single_label.txt
    no_filtered_protocol_ps_pi_mml_c_single_label: deduplicated_no_filtered_protocol_ps_pi_mml_c_single_label.txt
    no_filtered_ps_pi_desc_c_mml_c_single_label: deduplicated_no_filtered_ps_pi_desc_c_mml_c_single_label.txt
    no_filtered_protocol_ps_pi_desc_c_mml_c_single_label: deduplicated_no_filtered_protocol_ps_pi_desc_c_mml_c_single_label.txt
input_concept_files:
    filtered_pedia: filtered_Pediatric_Input_Concepts.txt
    filtered_adult: filtered_Adult_Input_Concepts.txt
    filtered_gener: filtered_General_Input_Concepts.txt
    filtered_out_pedia: filtered_out_Pediatric_Input_Concepts.txt
    filtered_out_adult: filtered_out_Adult_Input_Concepts.txt
    filtered_out_gener: filtered_out_General_Input_Concepts.txt
    pedia: Pediatric_Input_Concepts.txt
    adult: Adult_Input_Concepts.txt
    gener: General_Input_Concepts.txt
metric:
    similarity: cosine
output:
    fit:
        mm:
            sign_count: MetaMap_sign_count.txt
            sign_hist_count: MetaMap_sign_hist_count.txt
            top1: MetaMap_top1s.txt
            top3: MetaMap_top3s.txt
            top5: MetaMap_top5s.txt
            sign: MetaMap_Selected_Sign
            sign_hist: MetaMap_Selected_Sign_Hist
        mml:
            top1: MetaMapLite_top1s.txt
            top3: MetaMapLite_top3s.txt
            top5: MetaMapLite_top5s.txt
            sign_count: MetaMapLite_sign_count.txt
            sign_hist_count: MetaMapLite_sign_hist_count.txt
word_embed:
    txt: True
    concept: False
    protocol: True
    non_filter: True
    filtered: False
    filtered_out: False
bert_eval:
    eval_dir: bert_eval
    eval_unique_dir: bert_unique_eval
    filtered_text_samples: filtered_text_samples.txt
    filtered_text_labels: filtered_text_labels.txt
    filtered_out_text_samples: filtered_out_text_samples.txt
    filtered_out_text_labels: filtered_out_text_labels.txt
    filtered_concept_samples: filtered_concept_samples.txt
    filtered_concept_labels: filtered_concept_labels.txt
    filtered_out_concept_samples: filtered_out_concept_samples.txt
    filtered_out_concept_labels: filtered_out_concept_labels.txt
    filtered_samples: filtered_samples.txt
    filtered_labels: filtered_labels.txt
    filtered_out_samples: filtered_out_samples.txt
    filtered_out_labels: filtered_out_labels.txt
    label_text: label_text.txt
    label_concept: label_concept.txt
    label_text_concept: label_text_concept.txt
    train_sample: filtered_samples_train.txt
    train_label: filtered_labels_train.txt
    eval_sample: filtered_samples_eval.txt
    eval_label: filtered_labels_eval.txt
    test_sample: filtered_samples_test.txt
    test_label: filtered_labels_test.txt
#    init_dir: pretrained_emsbert_models
#    init_dir: mobilebert
    init_dir: NCBI_BERT_pubmed_mimic_uncased_L-12_H-768_A-12
    init_config: bert_config.json
    init_vocab: vocab.txt
#    init_ckpt: mobilebert_variables.ckpt
    init_ckpt: bert_model.ckpt
#    init_ckpt: model.ckpt-50000
    max_seq_length: 128
    model_dir: w-concept_no-shuffle_no-cosine_msl128_bs8_unique  # data, shuffle, msl, cos, bs -> tfrecord/result
    interleave_label: False
    interleave_freq: 1000
    cos_loss: False
    include_concept: False
    sts: True
    update_train_tfrecord: True
    update_eval_tfrecord: True
    update_test_tfrecord: True
    do_lower_case: True
    init_checkpoint: True
    do_train: False
    do_eval: False
    do_predict: True
    do_predict_miss: False
    output_dir: output
    export_dir: export
    tflite_dir: tflite
    saved_model_ts: 1639165068
    use_tpu: False
    tpu_name: None
    tpu_zone: None
    gcp_project: None
    master_url: ""
    num_tpu_cores: 8
    save_checkpoints_steps: 50000
    iterations_per_loop: 50000
    keep_checkpoint_max: 500
    train_batch_size: 8
    eval_batch_size: 1
    predict_batch_size: 1
    num_train_epochs: 10
    warmup_proportion: 0.03
    lr: 0.00005
    task_name: ems
    num_classes: 47
shuffle_split: False
init_seed: 2587
TF_CPP_MIN_LOG_LEVEL: 3
tf_log_level: info
cuda_device: 0
